### ISSUE TITLE
Research Logging Tools and Services

### ISSUE THREAD

**Issue by mlw6607** [bikelomatic-complexity/planning#130]

**Comment by JRJurman** [comment]
Look into what google analytics gives us

**Comment by mlw6607** [comment]
Using google analytics would allow us to wrap client-side events and send them through the google analytics API automatically. This is fine if we just want client-side, online logging, but it is not an all inclusive logging solution.

**Comment by mlw6607** [comment]
[client side logging strategy](]https://auth0.com/blog/2015/08/25/logging-and-debugging-in-react-with-flux-replaying-your-users-actions/)
