### ISSUE TITLE
High Priority Use Case Sheets

### ISSUE THREAD

**Issue by JRJurman** [bikelomatic-complexity/planning#29]
- [x] Save Route Data For Offline
- [x] Create Account (Ethan)
- [x] Create Narratives
- [x] View Tours (Matt)
- [x] Flag Content (Jesse) 
- [x] Research Tours (Steve)
- [x] Moderate Narratives (Ethan)
- [x] Delete Accounts (Matt)
- [x] Download Map Data - USBRS (Jesse)

**Comment by JRJurman** [comment]
https://drive.google.com/drive/u/1/folders/0B0Lbt78e0bnqRm5SaDFjZFRKWEk

**Comment by ethanjurman** [comment]
With John
- [ ] View tours
- [ ] Create tours
- [ ] Research tours
- [ ] Write narratives
- [ ] Register accounts
