### ISSUE TITLE
White-list of Manufacturers and OS Versions

### ISSUE THREAD

**Issue by JRJurman** [bikelomatic-complexity/planning#31]

**Comment by mlw6607** [comment]
Look into Cordova, and determine any OS specific concerns

**Comment by stevekroh** [comment]
- We've confirmed the app runs on the iPhone 4 & 5 emulator.
- We've confirmed the app runs on Android Lolipop & Marshmallow.
- There are some inconsistencies on Android

- We need to create a compatibility matrix 
- We need to investigate iPhone 3 & 6.
- We need to test older android devices

**Comment by JRJurman** [comment]
- [] Confirm this list with John
