### ISSUE TITLE
Implement Service.ViewInfo

### ISSUE THREAD

**Issue by mlw6607** [bikelomatic-complexity/planning#72]

**Comment by JRJurman** [comment]
- [ ] ensure all data in the data dictionary is displayed
- [ ] grab data from the database server
- [ ] add mock buttons for the checkin
- [ ] move website field to top
- [ ] List the timezone for the hours

**Comment by JRJurman** [comment]
Add service should pull the default timezone, and attach it to the cards.

**Comment by JRJurman** [comment]
Use phone's timezone as a default

**Comment by ethanjurman** [comment]
Closed with Timezone PR
