### ISSUE TITLE
Complete project information survey form

### ISSUE THREAD

**Issue by stevekroh** [bikelomatic-complexity/planning#9]
- [x] You need to come up with a list of descriptive terms and ask Dr. Vallino for approval.
- [ ] Domain name for Kurt

**Comment by stevekroh** [comment]
BUMP

**Comment by JRJurman** [comment]
Keywords are :
Bicycle Travel,
Bicycle Route Navigation,
Crowd sourced bicycle travel services,
Bicycle Touring Routes,
Mobile App,
Web Application
